[toolchain]
solana_version = "2.1.16"
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
review = "ESCRythK359iqXTANRrZ1h6VnVuk2R713ioAuweXGvaB"

[programs.devnet]
review = "ESCRythK359iqXTANRrZ1h6VnVuk2R713ioAuweXGvaB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"
