[toolchain]
solana_version = "2.1.16"
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
review = "MeqFmqmKwRW7tBX6ta4Zyw9ZFNvGW7g5W7X8EVygfLG"

[programs.devnet]
review = "MeqFmqmKwRW7tBX6ta4Zyw9ZFNvGW7g5W7X8EVygfLG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"
